---
title: "Preparation for Table 1"
author: "Jeremy Selva"
webr:
  # resources:
  #   - data/opt_data.rds
  packages:
    - reactable
    - gtsummary
    - broom
  repos:
    - https://ddsjoberg.r-universe.dev/gtsummary
---

{{< include ../_extensions/r-wasm/live/_knitr.qmd >}}
{{< include ../_extensions/r-wasm/live/_gradethis.qmd >}}

In this tutorial, we try to create a table that is close to [Table 1](https://www.nejm.org/cms/10.1056/NEJMoa062249/asset/c676621f-111e-4299-a7a3-082bbe922f9a/assets/images/large/nejmoa062249_t1.jpg){target="_blank"} from the journal [Treatment of Periodontal Disease and the Risk of Preterm Birth](https://www.nejm.org/doi/full/10.1056/NEJMoa062249){target="_blank"}.

We start first by choosing the relevant columns to make Table 1.

```{webr}
#| label: load opt data for table 1
#| envir: setup_table_1
#| autorun: true
opt_data <- readRDS("data/opt_data.rds") |> 
  dplyr::select(
    c("PID", "Group", 
      "Age", "White", "Black", "Hisp", "Education",
      "Prev.preg","Any.live.ptb.sb.sp.ab.in.ab",
      "previous_live_preterm_birth",
      "Spont.ab", "Induced.ab", "Any.stillbirth",
      "Any.live.ptb.sb.sp.ab.in.ab", 
      "Diabetes", "Hypertension", "Use.Alc")
  )
```

As the final output looks complex, let's break the task down to simpler tasks.

## Age, Race and Education Data

This task involves creating a summary table for age, race and number of years of education stratified by treatment group.

Here is the dataset required.

```{webr}
#| label: load opt data for age summary table
#| envir: setup_table_1
#| autorun: true
opt_age_race_data <- opt_data |> 
  dplyr::select(
    c("PID", "Group", 
      "Age", "White", "Black", "Hisp", "Education")
  )

opt_age_race_data |> 
  reactable::reactable(
    filterable = TRUE,
    paginationType = "jump",
    defaultPageSize = 5,
    minRows = 5)
```

## Using `tbl_summary`

Let's try to build a summary table from `opt_age_race_data` using the default parameters of [`gtsummary::tbl_summary`](https://www.danieldsjoberg.com/gtsummary/reference/tbl_summary.html){target="_blank"}. We can see that table is giving a descriptive statistics of the overall population. It even display the statistics the patient ID.

```{webr}
#| caption: age race and education basic table
#| label: age race and education basic table default parameters
#| envir: setup_table_1
opt_age_race_table <- opt_age_race_data |>
  gtsummary::tbl_summary()

opt_age_race_table
```

### `include` and `by` parameter

To exclude the patient ID being displayed, we set the parameter `include` a vector of column names to include in the summary table. To stratify the table by treatment group, we set the parameter `by = "Group"`.

```{webr}
#| caption: age race and education basic table
#| label: age race and education basic table with include and by
#| envir: setup_table_1
opt_age_race_table <- opt_age_race_data |>
  gtsummary::tbl_summary(
    include = c("Age", "White", "Black", "Hisp", "Education"),
    by = "Group"
  )

opt_age_race_table
```

### `type` parameter

Observe that the (continuous) variable `Age` is expressed as Median (Q1, Q3) while categorical variables are expressed as n (%). Variables with two categories (dichotomous) like `White` and `Hisp` are displayed differently to those with multiple categories like `Education`.

We can use the function [`gtsummary::assign_summary_type`](https://www.danieldsjoberg.com/gtsummary/reference/assign_summary_type.html){target="_blank"} to identify the default summary type for each variable

```{webr}
#| caption: view summary type
#| label: find default summary type
#| envir: setup_table_1
summary_type <- opt_age_race_data |>
  gtsummary::assign_summary_type(
    variables = c("Group" ,"Age", "White", 
                  "Black", "Hisp", "Education"),
    value =  NULL
  )

summary_type
```

On the other hand, the `type` parameter in the [`gtsummary::tbl_summary`](https://www.danieldsjoberg.com/gtsummary/reference/tbl_summary.html){target="_blank"} allows us to specify the summary type for each variable. The `type` parameter accepts a [list of formulas](https://www.danieldsjoberg.com/gtsummary/reference/syntax.html#formula-and-list-selectors){target="_blank"} as input.

Below is an example which we change the variable `White` and `Black` from dichotomous to categorical.

```{webr}
#| caption: age race and education basic assign type
#| label: age race and education basic table assign with type
#| envir: setup_table_1
opt_age_race_table <- opt_age_race_data |>
  gtsummary::tbl_summary(
    include = c("Age", "White", "Black", "Hisp", "Education"),
    type = list(
      c("White", "Black") ~ "categorical"
    ),
    by = "Group"
  )

opt_age_race_table
```

### `statistics` parameter

Next, we need to ensure that 
-  age is expressed in "means±SD". 
-  race and education is expressed in "no. (%)" (already done in default mode).

This can be achieved by using the `statistic` parameter which help users specify the statistics presented in the table. Like the `type` parameter, it accepts a [list of formulas](https://www.danieldsjoberg.com/gtsummary/reference/syntax.html#formula-and-list-selectors){target="_blank"} as input.

Below are some examples on how it can be done.

::: {.panel-tabset}

### 
Click on the different tabs.

### Variable Names

We can list each variable individually as a character vector.

```{webr}
#| caption: age race and education basic table statistics list all variables
#| label: age race and education basic table attempt present statistics by variable name
#| envir: setup_table_1
opt_age_race_table <- opt_age_race_data |>
  gtsummary::tbl_summary(
    include = c(
      "Age", "White", "Black", "Hisp", "Education",
    ),
    statistic = list(
      c("Age") ~ "{mean}±{sd}",
      c("White", "Black", "Hisp", "Education") ~ "{n} ({p})"
    ),
    by = "Group"
  )

opt_age_race_table
```

### Use Helpers

We can use `all_` helper functions like [`gtsummary::all_continuous()`](https://www.danieldsjoberg.com/gtsummary/reference/select_helpers.html){target="_blank"} and [`gtsummary::all_categorical()`](https://www.danieldsjoberg.com/gtsummary/reference/select_helpers.html){target="_blank"} to make the code concise.

```{webr}
#| caption: age race and education basic table statistics list all variables
#| label: age race and education basic table attempt present statistics by helper function
#| envir: setup_table_1
opt_age_race_table <- opt_age_race_data |>
  gtsummary::tbl_summary(
    include = c(
      "Age", "White", "Black", "Hisp", "Education",
    ),
    statistic = list(
      gtsummary::all_continuous() ~ "{mean}±{sd}",
      gtsummary::all_categorical() ~ "{n} ({p})"
    ),
    by = "Group"
  )

opt_age_race_table
```

:::

It can be observed that the displayed values `{mean}±{sd}` and `{n} ({p})` are interpreted using [glue::glue()](https://glue.tidyverse.org/reference/glue.html){target="_blank"} syntax: a name that appears between curly brackets will be interpreted as a function name and the formatted result of that function will be placed in the table.

In `gtsummary`, some pre-calculated statistics available for display are

For categorical/dichotomous variable:

-  {n} for frequency.
-  {N} for denominator.
-  {p} for percent.

For continuous variable:

-  {median} for median. 
-  {mean} for mean. 
-  {sd} for standard deviation. 
-  {min} for minimum.
-  {max} for maximum.
-  {p##} for percentile where ## is an integer from 0 to 100.\n For example, {p25} is the 25th percentile calculating using `p25: quantile(probs=0.25, type=2)`.

A full list is provided [here](https://www.danieldsjoberg.com/gtsummary/reference/tbl_summary.html#statistic-argument){target="_blank"}.

Feel free to experiment with the different statistics below.

::: {.panel-tabset}

### 
Click on the different tabs.

### Single Line

```{webr}
#| caption: age race and education basic table different stats
#| label: age race and education basic table attempt different stats single line
#| envir: setup_table_1
opt_age_race_table <- opt_age_race_data |>
  gtsummary::tbl_summary(
    include = c("Age", "White", "Black", "Hisp", "Education"),
    statistic = list(
      gtsummary::all_continuous() ~ "{median} ({p25}, {p75})",
      gtsummary::all_categorical() ~ "{n}/{N} ({p}%)"
    ),
    by = "Group",    
  )

opt_age_race_table
```

### Multiple Line

Sometimes, there may be a need to display continuous variables statistical summaries in multiple lines. To do that, you can change the variable `type` from `continuous` to `continuous2`.

```{webr}
#| caption: age race and education basic table different stats
#| label: age race and education basic table attempt different stats multiple line
#| envir: setup_table_1
opt_age_race_table <- opt_age_race_data |>
  gtsummary::tbl_summary(
    include = c("Age", "White", "Black", "Hisp", "Education"),
    type = list("Age" ~ "continuous2"),
    statistic = list(
      "Age" ~ c(
        "{mean}±{sd}",
        "{median} ({p25}, {p75})"
      ),
      gtsummary::all_categorical() ~ "{n}/{N} ({p}%)"
    ),
    by = "Group",    
  )

opt_age_race_table
```

:::

### Formatting in `gtsummary`

Before we get to the `digits` parameter, let's take a look at some default formatting from `gtsummary`

::: {.panel-tabset}

#### 
Click on the different tabs.

#### style_number()

[`gtsummary::style_number`](https://www.danieldsjoberg.com/gtsummary/reference/style_number.html){target="_blank"} is the default style that `gtsummary` used internally to style the number. It rounds numbers to a fixed number of decimal places specified by the `digits` argument.

```{webr}
#| caption: style number in gtsummary
#| label: style number in gtsummary simple
c(0.111, 12.3) |> gtsummary::style_number(digits = 2)
```

It has many flexible parameter to use and explore. The `digits` parameter can accept a vector of numbers to indicate how many decimal places to express for each number.

```{webr}
#| caption: style number in gtsummary
#| label: style number in gtsummary advanced
c(1110, 1200000.36, NA, 0.25) |> 
  gtsummary::style_number(
    digits = c(2, 0, 0, 5),
    big.mark = ",",
    decimal.mark = ".",
    scale = 0.001,
    prefix = "$",
    suffix = "K",
    na = "Not Applicable"
  )

```

#### style_sigfig()

[`gtsummary::style_sigfig`](https://www.danieldsjoberg.com/gtsummary/reference/style_sigfig.html){target="_blank"} rounds numbers to a minimum number of significant figures (significant digits) via `digits`, adapting the decimal count dynamically depending on the magnitude of the number.

```{webr}
#| caption: style sigfig in gtsummary
#| label: style sigfig in gtsummary simple
c(0.111, 12.3) |> gtsummary::style_sigfig(digits = 2)
```

Unlike [`gtsummary::style_number`](https://www.danieldsjoberg.com/gtsummary/reference/style_number.html){target="_blank"}, the `digits` parameter can only accept one number.

```{webr}
#| caption: style sigfig in gtsummary
#| label: style sigfig in gtsummary advanced
c(1110, 1200000.36, NA, 0.25) |> 
  gtsummary::style_sigfig(
    digits = 2,
    big.mark = ",",
    decimal.mark = ".",
    scale = 0.001,
    prefix = "$",
    suffix = "K",
    na = "Not Applicable"
  )

```

#### style_percent()

[`gtsummary::style_percent`](https://www.danieldsjoberg.com/gtsummary/reference/style_percent.html){target="_blank"} is the default style that `gtsummary` used internally to style percentages in proportions of categorical variables.

Observe that 

- All values are multiplied by 100.
- Negative values are set to `NA`.
- Positive numbers less than 0.1% are represented as `<0.1`.   
- Numbers less than 10% (exclusive) are rounded to `digits + 1` places.

```{webr}
#| caption: style percent in gtsummary
#| label: style percent in gtsummary simple
percent_vals <- c(
  -1, 0, 
  0.0001, 0.0005,
  0.001 , 0.005, 
  0.01, 0.05,
  0.10, 0.445, 0.99, 1, 1.45
)
  
percent_vals |> 
  gtsummary::style_percent(digits = 0)
```

#### style_ratio()

[`gtsummary::style_ratio`](https://www.danieldsjoberg.com/gtsummary/reference/style_sigfig.html){target="_blank"} is the default style that `gtsummary` used internally to format relative risk and odds ratio.

Observe that 

- Values between -1 and 1 will display `digits` number of significant digits based on [`gtsummary::style_sigfig`](https://www.danieldsjoberg.com/gtsummary/reference/style_sigfig.html){target="_blank"}.
- Values greater than 1 (or less than -1) will display `digits + 1` number of significant digits based on [`gtsummary::style_sigfig`](https://www.danieldsjoberg.com/gtsummary/reference/style_sigfig.html){target="_blank"}.

```{webr}
#| caption: style ratio in gtsummary
#| label: style ratio in gtsummary simple
ratio_vals <- c(
  -101.234, -12.345,
  -1.1234, -0.9, -0.123,
  0,
  0.123, 0.9, 
  1,
  1.1234, 12.345, 101.234
)
  
ratio_vals |> 
  gtsummary::style_ratio(digits = 2)
```

#### style_pvalue()

[`gtsummary::style_pvalue`](https://www.danieldsjoberg.com/gtsummary/reference/style_pvalue.html){target="_blank"} is the default style that `gtsummary` used internally to format *p* values.

Observe that 

- Values greater than 1 are set to `NA`.
- Negative values are set to `NA`.
- `digits` can only hold value `1`, `2`, or `3`. It determines how many decimal places are presented.
-  High *p* values have a limit based on the value of `digits`.
   - When `digits` is `1`, values more than 0.9 is represented as `>0.9`.
   - When `digits` is `2`, values more than 0.99 is represented as `>0.99`.
   - When `digits` is `3`, values more than 0.999 is represented as `>0.999`.
- *p* values less than 0.001 are represented as `<0.001`.   

```{webr}
#| caption: p value in gtsummary
#| label: p value in gtsummary simple
pvals <- c(
  1.5, -1,
  1, 
  0.999, 0.99, 0.9,
  0.5, 0.25, 0.2,  
  0.10, 0.0999,
  0.01, 0.001, 
  0.00099, 0.0001, 0
)
  
pvals |> 
  gtsummary::style_pvalue(digits = 2)
```

:::

Similar to the above `style_*()`functions, `gtsummary` has [`label_style_*()`](https://www.danieldsjoberg.com/gtsummary/reference/label_style.html){target="_blank"} functions that takes the same inputs as the `style_*()`functions but returns a "wrapper" function that perform the styling.

::: {.panel-tabset}

#### 
Click on the different tabs.

#### label_style_number()

```{webr}
#| caption: label style number in gtsummary
#| label: label style number in gtsummary advanced
my_style <- gtsummary::label_style_number(
  digits = 1,
  big.mark = ",",
  decimal.mark = ".",
  scale = 0.001,
  prefix = "$",
  suffix = "K",
  na = "Not Applicable")

my_style(c(1110, 1200000.36, NA))
```

#### label_style_sigfig

```{webr}
#| caption: label style sigfig in gtsummary
#| label: label style sigfig in gtsummary advanced
my_style <- gtsummary::label_style_sigfig(
  digits = 2,
  big.mark = ",",
  decimal.mark = ".",
  scale = 0.001,
  prefix = "$",
  suffix = "K",
  na = "Not Applicable"
)

my_style(c(1110, 1200000.36, NA, 0.25))
```

#### label_style_percent

```{webr}
#| caption: label style percent in gtsummary
#| label: label style percent in gtsummary simple
my_style <- gtsummary::label_style_percent(
  digits = 0
)

percent_vals <- c(
  -1, 0, 
  0.0001, 0.0005,
  0.001 , 0.005, 
  0.01, 0.05,
  0.10, 0.445, 0.99, 1, 1.45
)

my_style(percent_vals)
```

#### label_style_ratio

```{webr}
#| caption: label style ratio in gtsummary
#| label: label style ratio in gtsummary simple
my_style <- gtsummary::label_style_ratio(
  digits = 2
)

ratio_vals <- c(
  -101.234, -12.345,
  -1.1234, -0.9, -0.123,
  0,
  0.123, 0.9, 
  1,
  1.1234, 12.345, 101.234
)

my_style(ratio_vals)
```

#### label_style_pvalue

```{webr}
#| caption: label style pvalue in gtsummary
#| label: label style pvalue in gtsummary simple
my_style <- gtsummary::label_style_pvalue(
  digits = 2
)

pvals <- c(
  1.5, -1,
  1, 
  0.999, 0.99, 0.9,
  0.5, 0.25, 0.2,  
  0.10, 0.0999,
  0.01, 0.001, 
  0.00099, 0.0001, 0
)

my_style(pvals)
```

:::

### `digits` parameter

If we take a look at ([Table 1](https://www.nejm.org/cms/10.1056/NEJMoa062249/asset/c676621f-111e-4299-a7a3-082bbe922f9a/assets/images/large/nejmoa062249_t1.jpg){target="_blank"} from the journal [Treatment of Periodontal Disease and the Risk of Preterm Birth](https://www.nejm.org/doi/full/10.1056/NEJMoa062249){target="_blank"}, the mean, standard deviation (sd) and percentage are expressed in 1 decimal place.

In `gtsummary`, we can specify the numerical format to display a given statistical result using the `digits` parameter. Though it accepts a [list of formulas](https://www.danieldsjoberg.com/gtsummary/reference/syntax.html#formula-and-list-selectors){target="_blank"} as input, it is also restricted based on what input is given to the `statistic` parameter.

Looking at the example below,

-  In the case of the statistic is `{mean} ({sd})`, passing the value `1` or `c(1, 1)` is the same as passing the output of `gtsummary::label_style_number(digits=1)` for both `{mean}` and `{sd}`.
-  In the case of the statistic is `{n} ({p})`, passing the value `c(0, 1)` is the same as passing the output of `gtsummary::label_style_number(digits=0)` for both `{n}` and `gtsummary::label_style_percent(digits=1)` for `{p}`.

```{webr}
#| caption: age race and education summary table with statistics formatting
#| label: age race and education summary table with statistics formatting
#| envir: setup_table_1
opt_age_race_table <- opt_age_race_data |>
  gtsummary::tbl_summary(
    include = c("Age", "White", "Black", "Hisp", "Education"),
    by = "Group",
    statistic = list(
      gtsummary::all_continuous() ~ "{mean}±{sd}",
      gtsummary::all_categorical() ~ "{n} ({p})"
    ),
    digits = list(
      gtsummary::all_continuous() ~ 1,
      gtsummary::all_categorical() ~ c(0, 1)
    )
  )

opt_age_race_table
```

### `label` parameter

Currently, the column names of the dataset `opt_age_race_data` are used as the descriptive labels in the output table. We can update the descriptive labels printed using the `label` parameter. It accepts a [list of formulas](https://www.danieldsjoberg.com/gtsummary/reference/syntax.html#formula-and-list-selectors){target="_blank"} as input.

In the example below, we rename the following to match the ([Table 1](https://www.nejm.org/cms/10.1056/NEJMoa062249/asset/c676621f-111e-4299-a7a3-082bbe922f9a/assets/images/large/nejmoa062249_t1.jpg){target="_blank"} in the publication.

-  `Age` to `Age - yr`.
-  `Hisp` to `Hispanic`.
-  `Education` to `Education - no. (%)`.

```{webr}
#| caption: age race and education summary table with label updates
#| label: age race and education summary table with label updates
#| envir: setup_table_1
opt_age_race_table <- opt_age_race_data |>
  gtsummary::tbl_summary(
    include = c("Age", "White", "Black", "Hisp", "Education"),
    by = "Group",
    label = list(
      "Age" ~ "Age - yr",
      "Hisp" ~ "Hispanic",
      "Education" ~ "Education - no. (%)"
    ),
    statistic = list(
      gtsummary::all_continuous() ~ "{mean}±{sd}",
      gtsummary::all_categorical() ~ "{n} ({p})"
    ),
    digits = list(
      gtsummary::all_continuous() ~ 1,
      gtsummary::all_categorical() ~ c(0, 1)
    )
  )

opt_age_race_table
```

## Variable Group Header

You will observe in [Table 1](https://www.nejm.org/cms/10.1056/NEJMoa062249/asset/c676621f-111e-4299-a7a3-082bbe922f9a/assets/images/large/nejmoa062249_t1.jpg){target="_blank"}, there is a group header added above `White`, `Black` and `Hispanic` called `Race or ethnic group - no. (%)"`. Unlike `Education`, we cannot create a categorical column `Race or ethnic group - no. (%)"` because some patients have mixed race/ethnicity (Both White and Hispanic). 

Instead, we can use [`add_variable_group_header`](https://www.danieldsjoberg.com/gtsummary/reference/add_variable_group_header.html){target="_blank"} function in `gtsummary` to insert a custom section header row into a summary table and indents a chosen group of variables underneath it.

In the example below, we indicate the desired header name to the `header` parameter and the column names to group to the `variables` parameter.

```{webr}
#| caption: age race and education summary table with group headers
#| label: age race and education summary table with group headers
#| envir: setup_table_1
opt_age_race_table <- opt_age_race_data |>
  gtsummary::tbl_summary(
    include = c("Age", "White", "Black", "Hisp", "Education"),
    by = "Group",
    label = list(
      "Age" ~ "Age - yr",
      "Hisp" ~ "Hispanic",
      "Education" ~ "Education - no. (%)"
    ),
    statistic = list(
      gtsummary::all_continuous() ~ "{mean}±{sd}",
      gtsummary::all_categorical() ~ "{n} ({p})"
    ),
    digits = list(
      gtsummary::all_continuous() ~ 1,
      gtsummary::all_categorical() ~ c(0, 1)
    )
  ) |> 
  gtsummary::add_variable_group_header(
    header = "Race or ethnic group - no. (%)",
    variables = c("White", "Black", "Hisp")
  )

opt_age_race_table
```

## *p* values

We then use [`gtsummary::add_p`](https://www.danieldsjoberg.com/gtsummary/reference/add_p.tbl_summary.html){target="_blank"} to add *p* values to tables created using [`gtsummary::tbl_summary`](https://www.danieldsjoberg.com/gtsummary/reference/tbl_summary.html){target="_blank"}.

Please note that [`gtsummary::add_p`](https://www.danieldsjoberg.com/gtsummary/reference/add_p.tbl_summary.html){target="_blank"} requires the R package [`broom`](https://broom.tidymodels.org/){target="_blank"} for it to work.

::: {.panel-tabset}

#### 
Click on the different tabs.

#### Defaults hidden

By default based on the documentation, as 

- the `by` variable used (`Group`) in [`gtsummary::tbl_summary`](https://www.danieldsjoberg.com/gtsummary/reference/tbl_summary.html){target="_blank"} has two variables (`Control` and `Treatment`).
- `group` variable in [`gtsummary::add_p`](https://www.danieldsjoberg.com/gtsummary/reference/add_p.tbl_summary.html){target="_blank"} is `NULL` (not doing paired *t* test).
- `adj.vars` variable in [`gtsummary::add_p`](https://www.danieldsjoberg.com/gtsummary/reference/add_p.tbl_summary.html){target="_blank"} is `NULL` (not doing ANCOVA).
- Each categorical groups to compare has at least 5 people. 

Wilcoxon rank-sum test (`wilcox.test`) is applied to all continuous variables and Pearson's Chi-squared Test for Count Data without continuity correction (`chisq.test.no.correct`) is applied to all categorical variables.

Also, the number of decimal place used for the *p* values by default is 1, hence we update the `pvalue_fun` input to `gtsummary::label_style_pvalue(digits = 2)`.

```{webr}
#| caption: age race and education summary table with p values
#| label: age race and education summary table with p values simple
#| envir: setup_table_1
opt_age_race_table <- opt_age_race_data |>
  gtsummary::tbl_summary(
    include = c("Age", "White", "Black", "Hisp", "Education"),
    by = "Group",
    label = list(
      "Age" ~ "Age - yr",
      "Hisp" ~ "Hispanic",
      "Education" ~ "Education - no. (%)"
    ),
    statistic = list(
      gtsummary::all_continuous() ~ "{mean}±{sd}",
      gtsummary::all_categorical() ~ "{n} ({p})"
    ),
    digits = list(
      gtsummary::all_continuous() ~ 1,
      gtsummary::all_categorical() ~ c(0, 1)
    )
  ) |> 
  gtsummary::add_variable_group_header(
    header = "Race or ethnic group - no. (%)",
    variables = c("White", "Black", "Hisp")
  )|> 
  gtsummary::add_p(
    pvalue_fun = gtsummary::label_style_pvalue(digits = 2)
  ) 

opt_age_race_table
```

#### Defaults explicit

```{webr}
#| caption: age race and education summary table with p values
#| label: age race and education summary table with p values advanced
#| envir: setup_table_1
opt_age_race_table <- opt_age_race_data |>
  gtsummary::tbl_summary(
    include = c("Age", "White", "Black", "Hisp", "Education"),
    by = "Group",
    label = list(
      "Age" ~ "Age - yr",
      "Hisp" ~ "Hispanic",
      "Education" ~ "Education - no. (%)"
    ),
    statistic = list(
      gtsummary::all_continuous() ~ "{mean}±{sd}",
      gtsummary::all_categorical() ~ "{n} ({p})"
    ),
    digits = list(
      gtsummary::all_continuous() ~ 1,
      gtsummary::all_categorical() ~ c(0, 1)
    )
  ) |> 
  gtsummary::add_variable_group_header(
    header = "Race or ethnic group - no. (%)",
    variables = c("White", "Black", "Hisp")
  )|> 
  gtsummary::add_p(
    test = list(
      gtsummary::all_continuous() ~ "wilcox.test",
      gtsummary::all_categorical() ~ "chisq.test.no.correct"
    ),
    test.args = list(
      gtsummary::all_tests("wilcox.test") ~ list(alternative = "two.sided", correct = TRUE)
    ),
    pvalue_fun = gtsummary::label_style_pvalue(digits = 2)
  ) 

opt_age_race_table
```

:::

List of comparison tests that available within `gtsummary` or ways to create custom statistical tests can be found [here](https://www.danieldsjoberg.com/gtsummary/reference/tests.html){target="_blank"}.

## Remove footnotes

Finally, we use [`gtsummary::remove_footnote_header`](https://www.danieldsjoberg.com/gtsummary/reference/modify_footnote2.html){target="_blank"} to remove any unnecessary footnote as this will be added in final stage.

```{webr}
#| caption: age race and education summary table remove footnotes
#| label: age race and education summary table remove footnotes
#| envir: setup_table_1
# add_p() needs R package broom
opt_age_race_table <- opt_age_race_data |>
  gtsummary::tbl_summary(
    include = c("Age", "White", "Black", "Hisp", "Education"),
    by = "Group",
    label = list(
      "Age" ~ "Age - yr",
      "Hisp" ~ "Hispanic",
      "Education" ~ "Education - no. (%)"
    ),
    statistic = list(
      gtsummary::all_continuous() ~ "{mean}±{sd}",
      gtsummary::all_categorical() ~ "{n} ({p})"
    ),
    digits = list(
      gtsummary::all_continuous() ~ 1,
      gtsummary::all_categorical() ~ c(0, 1)
    )
  ) |> 
  gtsummary::add_variable_group_header(
    header = "Race or ethnic group - no. (%)",
    variables = c("White", "Black", "Hisp")
  )|> 
  gtsummary::add_p(
    pvalue_fun = gtsummary::label_style_pvalue(digits = 2)
  ) |> 
  gtsummary::remove_footnote_header()

opt_age_race_table
```

## Previous Pregnancy Data

In the next section, we proceed to build the previous pregnancy summary tables.

Here is the dataset needed.

```{webr}
#| label: previous pregnancy data for table 1
#| envir: setup_table_1
#| autorun: true
opt_previous_preg_data <- opt_data |> 
  dplyr::select(
    c("PID", "Group", 
      "Prev.preg",
      "previous_live_preterm_birth",
      "Spont.ab", "Induced.ab", "Any.stillbirth")
  )

opt_previous_preg_data |> 
  reactable::reactable(
    filterable = TRUE,
    paginationType = "jump",
    defaultPageSize = 5,
    minRows = 5)
```

## Missingness Display

It is observed that this time we have to deal with missing values. By default, [`tbl_summary`](https://www.danieldsjoberg.com/gtsummary/reference/tbl_summary.html){target="_blank"} display missing values titled as "Unknown" followed by presenting its counts (number of missing values).

```{webr}
#| caption: summary table with missingness
#| label: summary table with missingness
#| envir: setup_table_1
opt_previous_preg_table <- opt_previous_preg_data |>
  gtsummary::tbl_summary(
    include = c(
      "Prev.preg",
      "previous_live_preterm_birth",
      "Spont.ab", "Induced.ab", "Any.stillbirth"
    ),
    by = "Group"
  ) 

opt_previous_preg_table
```

There are three main parameters that you can use to control what is displayed for missing values. They are the `missing`, `missing_text`, and `missing_stat`.

-  The `missing` parameter accepts a [list of formulas](https://www.danieldsjoberg.com/gtsummary/reference/syntax.html#formula-and-list-selectors){target="_blank"} as input to help users specify any of three options `c("ifany", "no", "always")` to each of the variables to determine in what situation will the missing values be displayed. 
   - `ifany` means we only add a row for missingness if the variables have missing values.
   - `no` means we do not provide a row for missingness regardless if the variables have missing values or not.
   - `always` means we always provide a row for missingness regardless if the variables have missing values or not.
   - the default parameter for `missing` is all variables set to `ifany` or `missing = gtsummary::everything() ~ "ifany"`.
-  The `missing_text` parameter accepts a string to determine what label to display for missing value. It is currently set to "Unknown" by default.
-  The `missing_stats` parameter accepts a string to determine what statistic to show on missing row. It is currently set to "{N_miss}" by default to highlight the frequency of missing values. Summary statistics on the number of available to display are
   - `{N_obs}` for total number of observations.
   - `{N_miss}` for number of missing observations.
   - `{N_nonmiss}` for number of non-missing observations.
   - `{p_miss}` for percentage of observations missing.
   - `{p_nonmiss}` for percentage of observations not missing

To match [Table 1](https://www.nejm.org/cms/10.1056/NEJMoa062249/asset/c676621f-111e-4299-a7a3-082bbe922f9a/assets/images/large/nejmoa062249_t1.jpg){target="_blank"}, what we need is to simply set `missing = "no"`.

::: {.panel-tabset}

#### What we need

```{webr}
#| caption: summary table with missing as no
#| label: summary table with missing as no
#| envir: setup_table_1
opt_previous_preg_table <- opt_previous_preg_data |>
  gtsummary::tbl_summary(
    include = c(
      "Prev.preg",
      "previous_live_preterm_birth",
      "Spont.ab", "Induced.ab", "Any.stillbirth"
    ),
    by = "Group",
    missing = "no"
  ) 

opt_previous_preg_table
```

#### Let's experiment

```{webr}
#| caption: summary table with missingness playground
#| label: summary table with missingness playground
#| envir: setup_table_1
opt_previous_preg_table <- opt_previous_preg_data |>
  gtsummary::tbl_summary(
    include = c(
      "Prev.preg",
      "previous_live_preterm_birth",
      "Spont.ab", "Induced.ab", "Any.stillbirth",
      "Any.live.ptb.sb.sp.ab.in.ab"
    ),
    by = "Group",
    missing = list(
      "Prev.preg" ~ "always",
      "previous_live_preterm_birth" ~ "ifany",
      c("Spont.ab", "Induced.ab", 
        "Any.stillbirth") ~ "no"
    ),
    missing_text = "Missing",
    missing_stat = "{N_miss}/{N_obs} ({p_miss})"
  ) 

opt_previous_preg_table
```

:::

## Exercise

Let's make use of what we have learned in the previous section to replicate the previous pregnancy section in [Table 1](https://www.nejm.org/cms/10.1056/NEJMoa062249/asset/c676621f-111e-4299-a7a3-082bbe922f9a/assets/images/large/nejmoa062249_t1.jpg){target="_blank"}

Try out this exercise below. Ensure that

-  The labels are set correctly,
-  Statistics are displayed as counts (as integers) and percentages (in one decimal place).
-  *p* values are displayed in two decimal places.

```{webr}
#| setup: true
#| exercise: previous_pregnancy_table

opt_previous_preg_data <- readRDS("data/opt_data.rds") |> 
  dplyr::select(
    c("PID", "Group", 
      "Prev.preg",
      "previous_live_preterm_birth",
      "Spont.ab", "Induced.ab", "Any.stillbirth")
  )
```

```{webr}
#| exercise: previous_pregnancy_table
opt_previous_preg_data |>
  gtsummary::tbl_summary(
    include = c(
      "Prev.preg",
      "previous_live_preterm_birth",
      "Spont.ab", "Induced.ab", "Any.stillbirth"
    ),
    by = "Group",
    missing = "no",
    label = list(
      "Prev.preg" ~ _______,
      "previous_live_preterm_birth" ~ _______,
      "Spont.ab" ~ _______,
      "Induced.ab" ~ _______,
      "Any.stillbirth" ~ _______
    ),
    statistic = list(
      gtsummary::all_categorical() ~ _______
    ),
    digits = list(
      gtsummary::all_categorical() ~ _______
    )
  ) |> 
  gtsummary::add_variable_group_header(
    header = _______,
    variables = c(
      "Prev.preg",
      "previous_live_preterm_birth",
      "Spont.ab", "Induced.ab", "Any.stillbirth"
    )
  ) |> 
  gtsummary::add_p(
    pvalue_fun = _______
  ) |> 
  gtsummary::remove_footnote_header()
```

::: { .hint exercise="previous_pregnancy_table"}
::: { .callout-note collapse="false"}
## Hint

Take a look at how age race and education summary table is created and copy its parameters to the previous pregnancy table.

:::

:::

::: { .solution exercise="previous_pregnancy_table"}
::: { .callout-tip collapse="false"}
## Fully worked solution:

```{webr}
#| exercise: previous_pregnancy_table
#| solution: true
opt_previous_preg_data |>
  gtsummary::tbl_summary(
    include = c(
      "Prev.preg",
      "previous_live_preterm_birth",
      "Spont.ab", "Induced.ab", "Any.stillbirth"
    ),
    by = "Group",
    missing = "no",
    label = list(
      "Prev.preg" ~ "Any pregancy",
      "previous_live_preterm_birth" ~ "Live preterm birth",
      "Spont.ab" ~ "Spontaneous abortion",
      "Induced.ab" ~ "Induced abortion",
      "Any.stillbirth" ~ "Stillbirth"
    ),
    statistic = list(
      gtsummary::all_categorical() ~ "{n} ({p})"
    ),
    digits = list(
      gtsummary::all_categorical() ~ c(0, 1)
    )
  ) |> 
  gtsummary::add_variable_group_header(
    header = "Previous pregnancies - no. (%)",
    variables = c(
      "Prev.preg",
      "previous_live_preterm_birth",
      "Spont.ab", "Induced.ab", "Any.stillbirth"
    )
  )|> 
  gtsummary::add_p(
    pvalue_fun = gtsummary::label_style_pvalue(digits = 2)
  ) |> 
  gtsummary::remove_footnote_header()
```

:::

:::

```{webr}
#| exercise: previous_pregnancy_table
#| check: true
gradethis::grade_this_code()
```

## Clinical Data

In the next section, we proceed to build the clinical summary tables.

Here is the dataset needed.

```{webr}
#| label: clinical data for table 1
#| envir: setup_table_1
#| autorun: true
opt_clinical_data <- opt_data |> 
  dplyr::select(
    c("PID", "Group", 
      "Diabetes", "Hypertension", "Use.Alc")
  )

opt_clinical_data |> 
  reactable::reactable(
    filterable = TRUE,
    paginationType = "jump",
    defaultPageSize = 5,
    minRows = 5)
```

## Customised *p* value format

Let's create the clinical summary table using [`tbl_summary`](https://www.danieldsjoberg.com/gtsummary/reference/tbl_summary.html){target="_blank"}.

```{webr}
#| caption: clinical summary table with modified p value
#| label: clinical summary table without modified p value
#| envir: setup_table_1
opt_clincal_table <- opt_clinical_data |>
  gtsummary::tbl_summary(
    include = c("Diabetes", "Hypertension", "Use.Alc"),
    by = "Group",
    missing = "no",
    label = list(
      "Diabetes" ~ "Diabetes",
      "Hypertension" ~ "Chronic hypertension",
      "Use.Alc" ~ "Self-reported alcohol use"
    ),
    statistic = list(
      gtsummary::all_continuous() ~ "{mean}±{sd}",
      gtsummary::all_categorical() ~ "{n} ({p})"
    ),
    digits = list(
      gtsummary::all_continuous() ~ 1,
      gtsummary::all_categorical() ~ c(0, 1)
    )
  ) |> 
  gtsummary::add_variable_group_header(
    header = "Coexisiting medical condition - no. (%)",
    variables = c("Diabetes", "Hypertension", "Use.Alc")
  ) |> 
  gtsummary::add_p(
    pvalue_fun = gtsummary::label_style_pvalue(digits = 2)
  ) |> 
  gtsummary::remove_footnote_header()

opt_clincal_table
```

It is observed that using `pvalue_fun = gtsummary::label_style_pvalue(digits = 2)` give `>0.99` for `Self-reported alcohol use`. One way to match [Table 1](https://www.nejm.org/cms/10.1056/NEJMoa062249/asset/c676621f-111e-4299-a7a3-082bbe922f9a/assets/images/large/nejmoa062249_t1.jpg){target="_blank"} is to create a customised function to control how *p* values are reported.

Below is an example of how a customised function `p_value_style` is created and used to ensure it matches the *p* value reporting style you see in [Table 1](https://www.nejm.org/cms/10.1056/NEJMoa062249/asset/c676621f-111e-4299-a7a3-082bbe922f9a/assets/images/large/nejmoa062249_t1.jpg){target="_blank"} and later [Table 2](https://www.nejm.org/cms/10.1056/NEJMoa062249/asset/b981f44a-0873-42d4-ad60-d7545e1f63cb/assets/images/large/nejmoa062249_t2.jpg){target="_blank"}.

```{webr}
#| caption: clinical summary table with modified p value
#| label: clinical summary table with modified p value
#| envir: setup_table_1
p_value_style <- function(x) {
  dplyr::case_when(
    x == 1 ~ "1.0",
    x > 0.99 & x < 1 ~ "0.99",
    .default = gtsummary::style_pvalue(x, digits = 2)
  )
}
opt_clincal_data <- opt_data |>
  gtsummary::tbl_summary(
    include = c("Diabetes", "Hypertension", "Use.Alc"),
    by = "Group",
    missing = "no",
    label = list(
      "Diabetes" ~ "Diabetes",
      "Hypertension" ~ "Chronic hypertension",
      "Use.Alc" ~ "Self-reported alcohol use"
    ),
    statistic = list(
      gtsummary::all_continuous() ~ "{mean}±{sd}",
      gtsummary::all_categorical() ~ "{n} ({p})"
    ),
    digits = list(
      gtsummary::all_continuous() ~ 1,
      gtsummary::all_categorical() ~ c(0, 1)
    )
  ) |> 
  gtsummary::add_variable_group_header(
    header = "Coexisiting medical condition - no. (%)",
    variables = c("Diabetes", "Hypertension", "Use.Alc")
  ) |> 
  gtsummary::add_p(
    pvalue_fun = p_value_style
  ) |> 
  gtsummary::remove_footnote_header()

opt_clincal_data
```

## Steps ahead

From this section, we have managed to create the summary table for age, race and education, previous pregnancy and clinical for [Table 1](https://www.nejm.org/cms/10.1056/NEJMoa062249/asset/c676621f-111e-4299-a7a3-082bbe922f9a/assets/images/large/nejmoa062249_t1.jpg){target="_blank"}. In the next section, we proceed to combine the three tables with further modification to match [Table 1](https://www.nejm.org/cms/10.1056/NEJMoa062249/asset/c676621f-111e-4299-a7a3-082bbe922f9a/assets/images/large/nejmoa062249_t1.jpg){target="_blank"}.
